version: '3.9'

services:
  flask-app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    environment:
      FLASK_ENV: development
      FLASK_APP: app.py
      FLASK_RUN_PORT: 8000
    volumes:
      - .:/app
    command: flask run --host=0.0.0.0 --port=8000
